mode = "light"

pink = "#d7827e"
mauve = "#907aa9"
red = "#b4637a"
peach = "#d7827e"
yellow = "#ea9d34"
green = "#56949f"
teal = "#56949f"
blue = "#286983"
lavender = "#907aa9"

foreground = "#575279"
background = "#faf4ed"
dark_background = "#fffaf3"
darker_background = "#f4ede8"
lighter_background = "#f2e9e1"
dark_foreground = "#dfdad9"
light_foreground = "#797593"
selection = "#eee5dd"
muted = "#9893a5"
cyan = "#56949f"
magenta = "#907aa9"
bright_foreground = "#575279"
bright_yellow = "#ea9d34"
