# Prefer aptX Adaptive and high-quality codecs for A2DP, and auto-switch audio output to Bluetooth when connected.
# AAC is placed last due to transport acquisition failures on some devices.

monitor.bluez.properties = {
  bluez5.codecs = [ aptx_adaptive aptx_hd ldac aptx sbc_xq aac sbc ]
  bluez5.msbc-support = true
}

monitor.bluez.rules = [
  {
    matches = [
      {
        node.name = "~bluez_output.*"
      }
    ]
    actions = {
      update-props = {
        priority.session = 2500
      }
    }
  }
]
