# Prefer SBC-XQ over AAC for A2DP, and auto-switch audio output to Bluetooth when connected.

monitor.bluez.properties = {
  bluez5.codecs = [ ldac sbc_xq sbc aac ]
}

monitor.bluez.rules = [
  {
    matches = [
      {
        node.name = "~bluez_output.*"
      }
    ]
    actions = {
      update-props = {
        priority.session = 2500
      }
    }
  }
]
