mode = "light"

pink = "#ea76cb"
mauve = "#8839ef"
red = "#d20f39"
peach = "#fe640b"
yellow = "#df8e1d"
green = "#40a02b"
teal = "#179299"
blue = "#1e66f5"
lavender = "#7287fd"

foreground = "#4c4f69"
background = "#eff1f5"
dark_background = "#e3e4e8"
darker_background = "#d7d8dc"
lighter_background = "#dce0e8"
dark_foreground = "#9ca0b0"
light_foreground = "#5c5f77"
selection = "#ccd0da"
muted = "#acb0be"
cyan = "#179299"
magenta = "#ea76cb"
bright_foreground = "#4c4f69"
bright_yellow = "#df8e1d"
