rosewater = "#d0a69d"
flamingo = "#d19d9d"
pink = "#d99eca"
mauve = "#9e76d2"
red = "#c54762"
maroon = "#ce7c83"
peach = "#d58659"
yellow = "#c49a5f"
green = "#61a851"
teal = "#3f9ea3"
sky = "#45a7cd"
sapphire = "#4ca6b6"
blue = "#6489d2"
lavender = "#9fa9e6"
text = "#5b6074"
subtext1 = "#6b7083"
subtext0 = "#7a7f91"
overlay2 = "#81869a"
overlay1 = "#9297a8"
overlay0 = "#a3a8b7"
surface2 = "#b5bac6"
surface1 = "#c3c7d2"
surface0 = "#d2d5de"
base = "#edf0f4"
mantle = "#e7ebf0"
crust = "#e0e4eb"

cursor = "#9fa9e6"
foreground = "#5b6074"
background = "#edf0f4"
selection_foreground = "#5b6074"
selection_background = "#d8dde8"
color0 = "#c3c7d2"
color1 = "#c54762"
color2 = "#61a851"
color3 = "#c49a5f"
color4 = "#6489d2"
color5 = "#d99eca"
color6 = "#3f9ea3"
color7 = "#6b7083"
color8 = "#b5bac6"
color9 = "#c54762"
color10 = "#61a851"
color11 = "#c49a5f"
color12 = "#6489d2"
color13 = "#d99eca"
color14 = "#3f9ea3"
color15 = "#7a7f91"
