mode = "dark"

pink = "#ebbcba"
mauve = "#c4a7e7"
red = "#eb6f92"
peach = "#ebbcba"
yellow = "#f6c177"
green = "#9ccfd8"
teal = "#9ccfd8"
blue = "#31748f"
lavender = "#c4a7e7"

foreground = "#e0def4"
background = "#191724"
dark_background = "#1f1d2e"
darker_background = "#191724"
lighter_background = "#26233a"
dark_foreground = "#403d52"
light_foreground = "#908caa"
selection = "#302d44"
muted = "#6e6a86"
cyan = "#9ccfd8"
magenta = "#c4a7e7"
bright_foreground = "#e0def4"
bright_yellow = "#f6c177"
