[manager]
cwd = { fg = "#31748f" }
hovered = { reversed = true, bold = true }
preview_hovered = { underline = true }
find_keyword = { fg = "#9ccfd8", italic = true }
find_position = { fg = "#ebbcba", italic = true }
marker_copied = { fg = "#9ccfd8", bg = "#9ccfd8" }
marker_cut = { fg = "#ebbcba", bg = "#ebbcba" }
marker_marked = { fg = "#9ccfd8", bg = "#9ccfd8" }
marker_selected = { fg = "#e0def4", bg = "#e0def4" }
tab_active = { fg = "#191724", bg = "#908caa" }
tab_inactive = { fg = "#908caa", bg = "#403d52" }
count_copied = { fg = "#191724", bg = "#9ccfd8" }
count_cut = { fg = "#191724", bg = "#ebbcba" }
count_selected = { fg = "#191724", bg = "#e0def4" }
border_symbol = "│"
border_style = { fg = "#524f67" }

[mode]
normal_main = { fg = "#191724", bg = "#908caa", bold = true }
normal_alt = { fg = "#908caa", bg = "#403d52" }
select_main = { fg = "#191724", bg = "#ebbcba", bold = true }
select_alt = { fg = "#908caa", bg = "#403d52" }
unset_main = { fg = "#191724", bg = "#9ccfd8", bold = true }
unset_alt = { fg = "#908caa", bg = "#403d52" }

[status]
sep_left = { open = "", close = "" }
sep_right = { open = "", close = "" }
overall = {}
progress_label = { fg = "#e0def4", bold = true }
progress_normal = { fg = "#403d52", bg = "#26233a" }
progress_error = { fg = "#eb6f92", bg = "#26233a" }
perm_type = { fg = "#403d52" }
perm_read = { fg = "#9ccfd8" }
perm_write = { fg = "#eb6f92" }
perm_exec = { fg = "#9ccfd8" }
perm_sep = { fg = "#524f67" }

[pick]
border = { fg = "#31748f" }
active = { fg = "#c4a7e7", bold = true }
inactive = {}

[input]
border = { fg = "#e0def4" }
title = {}
value = {}
selected = { reversed = true }

[tasks]
border = { fg = "#403d52" }
title = {}
hovered = { underline = true }

[which]
mask = { bg = "#26233a" }
cand = { fg = "#31748f" }
rest = { fg = "#6e6a86" }
desc = { fg = "#ebbcba" }
separator = "  "
separator_style = { fg = "#403d52" }

[help]
on = { fg = "#31748f" }
run = { fg = "#c4a7e7" }
hovered = { reversed = true, bold = true }
footer = { fg = "#191724", bg = "#908caa" }

[notify]
title_info = { fg = "#9ccfd8" }
title_warn = { fg = "#f6c177" }
title_error = { fg = "#eb6f92" }

[filetype]
rules = [
    { mime = "image/*", fg = "#c4a7e7" },
    { mime = "{audio,video}/*", fg = "#f6c177" },
    { mime = "application/*zip", fg = "#eb6f92" },
    { mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", fg = "#eb6f92" },
    { mime = "application/{pdf,doc,rtf,vnd.*}", fg = "#9ccfd8" },
    { url = "*/", fg = "#31748f" },
    { url = "*", fg = "#e0def4" },
]

[confirm]
border = { fg = "#908caa" }
title = { fg = "#31748f" }
content = { fg = "#ebbcba" }
body = { fg = "red" }
list = { fg = "#e0def4" }
btn_yes = { reversed = true, fg = "#e0def4" }
btn_no = {}
btn_labels = ["  [Y]es  ", "  (N)o  "]

[cmp]
border = { fg = "#908caa" }
active = { reversed = true, fg = "#31748f" }
inactive = { fg = "#e0def4" }
