promptToReturnFromSubprocess: false
os:
    editPreset: "nvim"
git:
    diffRenderers:
        - colorArg: "always"
          command: "delta --{{ mode }} --paging=never"
gui:
    theme:
        activeBorderColor:
            - "{{ accent }}"
            - bold
        inactiveBorderColor:
            - "{{ muted }}"
        optionsTextColor:
            - "{{ accent }}"
        selectedLineBgColor:
            - "{{ selection }}"
        cherryPickedCommitBgColor:
            - "{{ muted }}"
        cherryPickedCommitFgColor:
            - "{{ accent }}"
        unstagedChangesColor:
            - "{{ red }}"
        defaultFgColor:
            - "{{ foreground }}"
        searchingActiveBorderColor:
            - "{{ yellow }}"
    authorColors:
        "*": "{{ magenta }}"
